### ISSUE TITLE
map: geolocate event venues

### ISSUE THREAD

**Issue by sayanee** [webuildsg/data#27]

**Comment by sayanee** [comment]
Example: https://github.com/cheeaun/walkabout-map/blob/master/index.js

thanks @cheeaun :heart_eyes:

**Comment by cheeaun** [comment]
FYI That script also generates a GeoJSON file 👍😎

**Comment by sayanee** [comment]
whoa :100: :heart_decoration:

**Comment by sayanee** [comment]
[code ref](https://github.com/cheeaun/walkabout-map/blob/master/index.js#L21): @cheeaun sometimes `d.results[0]` is `undefined` and hence cannot get `lat, long` for that location. Do you know why? Or how do you get the Lat / Long in those cases? I got back only 7 out of 28 locations' lat/long values.

**Comment by cheeaun** [comment]
@sayanee probably the [usage limits](https://developers.google.com/maps/documentation/geocoding/usage-limits)?

**Comment by sayanee** [comment]
`10 requests per second` ok :sweat_smile: 

Shall write the script to geocode 10 of them every 15 seconds then.

**Comment by cheeaun** [comment]
every second lah

**Comment by sayanee** [comment]
geojson done :+1: :100: :earth_asia: 

https://github.com/webuildsg/data/blob/gh-pages/public/data/events-per-location.geojson

**Comment by sayanee** [comment]
or [embed the geojson map directly](https://help.github.com/articles/mapping-geojson-files-on-github/#embedding-your-map-elsewhere) as github pages supports it

**Comment by sayanee** [comment]
![image](https://cloud.githubusercontent.com/assets/413879/11607083/14f6680e-9b74-11e5-9056-1e16c44b6012.png)
