### ISSUE TITLE
support https

### ISSUE THREAD

**Issue by sayanee** [webuildsg/data#31]
thanks @jsstrn :star:

**Comment by jsstrn** [comment]
You're most welcome! :+1:

**Comment by notthetup** [comment]
Moved the CloudFlare record from a `A` record to a `CNAME` record.

**Comment by sayanee** [comment]
:+1:  As a later date, the assets will have a protocol relative url with an absolute path #35 

<img width="1191" alt="screenshot 2015-12-07 09 28 19" src="https://cloud.githubusercontent.com/assets/413879/11617092/109733d6-9cc5-11e5-87fa-64b2f486f065.png">
