### ISSUE TITLE
Icons not included in repo

### ISSUE THREAD

**Issue by cheeaun** [webuildsg/data#34]
I tried running `npm run build` but getting an error when `jade`-ing the files:

```
Error: views\partials\graph-list.jade:5
    3|     a(href="/dataset/repos-per-week")
    4|       span
  > 5|         include ../icons/chart.jade
    6|       p.graph-name repos per week
    7|   li(class="searchable", data-index="events meetup week weeks")
    8|     a(href="/dataset/events-per-week")

ENOENT: no such file or directory
```

It looks like the icon files are not included in the repo?

**Comment by sayanee** [comment]
so wierd... the `icons` folder is in the `views` folder and i didn't even `.gitignore` it :/

let me investigate and push it in!

![image](https://cloud.githubusercontent.com/assets/413879/11613110/463b6d74-9c50-11e5-9d82-fe7a88c75eec.png)

**Comment by cheeaun** [comment]
:+1:
