### ISSUE TITLE
save graph as image for responsive graph on mobile

### ISSUE THREAD

**Issue by sayanee** [webuildsg/data#44]
http://techslides.com/save-svg-as-an-image

to be integrated within `npm run build` and replace [graph images](https://github.com/webuildsg/data/tree/gh-pages/public/img) for mobile view

**Comment by sayanee** [comment]
try https://github.com/sampumon/SVG.toDataURL

thanks @joerx

**Comment by sayanee** [comment]
<img width="887" alt="screen shot 2016-02-29 at 8 54 27 pm" src="https://cloud.githubusercontent.com/assets/413879/13395000/eade1f70-df26-11e5-8816-a58fcf78ad87.png">

thanks @cheeaun

**Comment by cheeaun** [comment]
Resolved by 7bc48d6854f8c82c4831075a05dd04d8c1effb6b. No longer need to save as image.

**Comment by sayanee** [comment]
:ghost: :tada:
