### ISSUE TITLE
fix favicon link

### ISSUE THREAD

**Issue by sayanee** [webuildsg/data#53]
Change from https://webuild.sg/public/favicon.ico to https://assets.webuild.sg/favicon.ico as the link is not correct and the favicon is not showing:

![image](https://cloud.githubusercontent.com/assets/413879/13636431/d85e1248-e63c-11e5-861a-ba0534b7d33d.png)

Steps to do:

1. Fork this repository to your account
- Create a new branch `fix-favicon-link`
- Find `https://webuild.sg/public/favicon.ico` and replace with `https://assets.webuild.sg/favicon.ico` in only `*.jade` files
- Note that you only need to amend `views/partials/head.jade` and the rest of the `*.html` files will be amended with the build process (explained later on below)
- Install `npm` packages with `npm install`
- Build the html files with `npm run build:html` and you will see more `html` files being edited
- You can do a `git status` to see all the changes
- Run the website locally with `npm start` and check all pages have the favicon
- Commit with a good message
- Send a pull request

Changes to your pull request:

1. In case you need to amend, just change the code and commit
- push to the same branch and the pull request will be updated!

**Comment by jsstrn** [comment]
Running `npm run build:html` will replace the new favicon link with the old one.

**Comment by sayanee** [comment]
closed with #54
